### ISSUE TITLE
Update name of repo to `substrate-front-end-tutorial`

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-front-end-tutorial#12]
I think we should update the name of this repo.

Since it teaches people to build the "substrate-ui-template", something like "substrate-ui-tutorial" makes sense to me.

@Tbaut thoughts?

**Comment by Tbaut** [comment]
Talking with the JS team, we want to go away from this "UI" names. I don't mind adding "tutorial", I'd keep the front-end though.

> Since it teaches people to build the "substrate-ui-template"

At least it teaches some part of it, why not rename substrate-ui-template -> substrate-font-end-template

**Comment by shawntabrizi** [comment]
We should do that if we want to avoid using UI, but quickly, what is the rational?

I chose UI because people were familiar with: https://github.com/paritytech/substrate-ui

And this new template is supposed to replace this product.

**Comment by Tbaut** [comment]
As I said in private, the wish was to not confuse ppl with the substrate ui. Happy to use "UI" if we want to deprecate "substrate ui".

**Comment by shawntabrizi** [comment]
Gav didn't want to change the name of his project for fear of further confusion with renaming and stuff.

We will go with `substrate-front-end-template` and `substrate-front-end-tutorial`

**Comment by JoshOrndorff** [comment]
Sounds like consensus has been reached. I'm assigning to @shawntabrizi because he has perms to do the renaming.
