### ISSUE TITLE
Can't connect to any chain

### ISSUE THREAD

**Issue by EdwardAThomson** [substrate-developer-hub/substrate-front-end-tutorial#14]
I was trying out this tutorial and have worked through parts 1-2 and 1-3, but in neither case could I connect to any chain.

"yarn;" and "yarn start;" seemed to work fine too. Node modules downloaded and the app opens in the browser but it constantly shows the loading wheel. This was in Firefox on a fresh Ubuntu VM.

I tried changing the endpoint in case the one in the repo didn't work. However, I'm confident that the endpoint in the repo (substrate.dev) works since I can seemingly connect to it via polkadot.js.org/apps.

Any pointers?

**Comment by Tbaut** [comment]
Thanks for the issue, I didn't keep up with the new polkadot-js/api releases.
I just tested with 1.1.1 and it's working fine. I'll do a PR in the next minutes.
